# Generated by Django 6.0.5 on 2026-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='categories', to='core.company', verbose_name='الشركات المرتبطة'),
        ),
    ]
