# Generated by Django 6.0.5 on 2026-06-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(blank=True, help_text='اتركه فارغاً ليكون العرض مفتوحاً/مستمراً', null=True, verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'صورة سلايدر',
                'verbose_name_plural': 'صور السلايدر',
                'ordering': ['-created_at'],
            },
        ),
    ]
