# Generated by Django 6.0.5 on 2026-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='رمز الجهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'جهاز إشعارات',
                'verbose_name_plural': 'أجهزة الإشعارات',
            },
        ),
    ]
